name: Release Drafter

on:
  push:
    # イベントで考慮するブランチ オプション、デフォルトはすべて
    branches:
      - main
  # # pull_request イベントは autolabeler のみで必要です。
  pull_request:
    # 以下のタイプのみがアクションによって処理されますが、デフォルトで全てに設定することも可能です。
    types: [opened, reopened, synchronize]
  # autolabeler がフォークからの PR をサポートするためには pull_request_target イベントが必要です。
  # pull_request_target:
  #   types: [opened, reopened, synchronize]

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      # (Optional) GitHub Enterprise では GHE_HOST 変数の設定が必要です。
      #- name: Set GHE_HOST
      #  run: |
      #    echo "GHE_HOST=${GITHUB_SERVER_URL##https:\/\/}" >> $GITHUB_ENV

      # Pull Requests が "main" にマージされる際に、次のリリースノートをドラフトで作成します。
      - uses: release-drafter/release-drafter@v5
        # (Optional) .github/からの相対パスで、使用する設定名を指定します。デフォルト: release-drafter.yml
        # with:
        #   config-name: my-config.yml
        #   disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}